#!/bin/bash
set -o errexit
export REACT_APP_BRAINFUCK_SCRIPT_FRONTEND_URL=$BRAINFUCK_SCRIPT_FRONTEND_URL
export REACT_APP_BRAINFUCK_SCRIPT_BACKEND_URL=$BRAINFUCK_SCRIPT_BACKEND_URL
npm install && npm run build